spring:
  application:
    name: mr_blue

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb

  sql:
    init:
      username: sa
      password:
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql

  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.type: trace